### PR TITLE
[dart-runtime] Update http: 0.13.4

### PR DESCRIPTION
**Pull request by daniloapr**
Update `http: 0.13.4` dependency in pubspec.

### CODE REVIEW

**Comment by lbguilherme** [comment]
`^0.13.0` already includes `^0.13.4`, pub will install the latest version given this constraint. Any reason to force it to only work with `^0.13.4`?

**Comment by lbguilherme** [comment]
Also, CI failed.

**Comment by dgadelha** [comment]
CI failed because this change requires a Flutter/Dart SDK upgrade ([#](https://github.com/sdkgen/sdkgen/runs/6009854570?check_suite_focus=true#step:5:42)):

```
The current Dart SDK version is 2.13.4.

Because sdkgen_runtime depends on http >=0.13.4 which requires SDK version >=2.14.0 <3.0.0, version solving failed.
```

**Comment by lbguilherme** [comment]
sdkgen currently supports Flutter 2.0.x and 2.2.x, those ship with Dart 1.12 and 1.13. For this to be approved we would need to drop support for Flutter before 2.5. This would be a breaking change.

**Pull request closed without merging**
